# -----------------------------------------------------------------------------
#  $Id: Makefile,v 1.9 2005/11/22 09:21:54 pbui Exp pbui $
# -----------------------------------------------------------------------------

#  Copyright (c) Peter Bui. All Rights Reserved.

#  For specific licensing information, please consult the COPYING file that
#  comes with the software distribution.  If it is missing, please contact the
#  author at peter.j.bui@gmail.com.   

# -----------------------------------------------------------------------------
#  Commands
# -----------------------------------------------------------------------------

SHELL    = /bin/sh
CC       = gcc
CXX      = g++

# -----------------------------------------------------------------------------
#  Environment
# -----------------------------------------------------------------------------

DATE	 = `date +%Y%m%d`
MACHINE	 = `uname -m`

# -----------------------------------------------------------------------------
#  Compiler and Linker Flags
# -----------------------------------------------------------------------------

CFLAGS  = -std=c99 -Wall -s -Os -D_BSD_SOURCE -D_DATE="\"$(DATE)\"" $(INCLUDES)
#CFLAGS   = -std=c99 -Wall -g -D_BSD_SOURCE -D_DATE="\"$(DATE)\"" $(INCLUDES)
CFLAGS  += -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 
CXXFLAGS = $(CFLAGS)
LDFLAGS	 = $(LIBS) -lm

# -----------------------------------------------------------------------------
#  Include and Library Paths
# -----------------------------------------------------------------------------

INCLUDES = -I.
LIBS	 = -L.

# -----------------------------------------------------------------------------
#  Package Options
# -----------------------------------------------------------------------------

PKGNAME  = $(ND_TGT)

# -----------------------------------------------------------------------------
#  Specific Targets and Objects
# -----------------------------------------------------------------------------

ND_OBJ   = nodoubt.o
ND_TGT   = nodoubt

TARGETS	 = $(ND_TGT)

# -----------------------------------------------------------------------------
#  File Extension Handlers
# -----------------------------------------------------------------------------

.SUFFIXES:	.cc .c .o

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<

.cc.o:
	$(CXX) $(CXXFLAGS) -o $@ -c $<

# -----------------------------------------------------------------------------
#  General Targets
# -----------------------------------------------------------------------------

all: 	$(TARGETS)

phony:	clean depend package update

clean:
	rm -f *.o *.core *.tar.gz $(TARGETS)-*

depend:
	rm -f Makefile.bak
	mv Makefile Makefile.bak
	sed '/^# DEPENDENCIES/,$$d' Makefile.bak > Makefile
	echo '# DEPENDENCIES' >> Makefile
	echo '' >> Makefile
	$(CC) -MM *.c >> Makefile
	echo '' >> Makefile
	echo -n '# ------------------------------------' >> Makefile
	echo '-----------------------------------------' >> Makefile

package: clean
	cd ..; tar -czvf "$(PKGNAME)-$(DATE).tar.gz" $(PKGNAME); cd -;

update: clean depend all

# -----------------------------------------------------------------------------
#  Specific Target Options
# -----------------------------------------------------------------------------

$(ND_TGT):	$(ND_OBJ)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(ND_OBJ)
	mv -f $@ $@-$(MACHINE)

# -----------------------------------------------------------------------------
#  Autogenerated Dependencies
# -----------------------------------------------------------------------------

# DEPENDENCIES

nodoubt.o: nodoubt.c nodoubt.h

# -----------------------------------------------------------------------------
